import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateMigrations1681876191422 implements MigrationInterface {
    name = 'UpdateMigrations1681876191422'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`aut_unique_username_type_deleted_at\` ON \`aut_credentials\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`createdBy\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`deletedBy\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`jobTitle\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`maxSalary\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`minSalary\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`updatedBy\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`createdBy\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`deletedBy\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`firstName\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`hireDate\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`lastName\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`updatedBy\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`createdBy\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`deletedBy\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`departmentName\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`updatedBy\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`createdBy\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`deletedBy\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`fromDate\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`toDate\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`updatedBy\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`createdBy\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`deletedBy\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`endDate\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`startDate\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`updatedBy\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`createdBy\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`deletedBy\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`sourceId\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`updatedBy\``);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`deleted_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`job_title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`min_salary\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`max_salary\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`deleted_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`first_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`last_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`phone_number\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`hire_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`deleted_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`department_name\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`deleted_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`from_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`to_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`deleted_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`start_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`end_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`updated_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`deleted_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`source_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`phone_number\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`aut_unique_username_type_deleted_at\` ON \`aut_credentials\` (\`username\`, \`type\`, \`deleted_at\`)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`aut_unique_username_type_deleted_at\` ON \`aut_credentials\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`source_id\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`deleted_by\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`end_date\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`start_date\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`deleted_by\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`time_off\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`to_date\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`from_date\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`deleted_by\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`salary\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`department_name\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`deleted_by\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`department\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`hire_date\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`last_name\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`first_name\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`deleted_by\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`employee\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`max_salary\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`min_salary\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`job_title\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`deleted_by\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`updated_by\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`created_by\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`job\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`updatedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`sourceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`phoneNumber\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`deletedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`createdBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`aut_credentials\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`updatedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`startDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`endDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`deletedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`createdBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`time_off\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`updatedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`toDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`fromDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`deletedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`createdBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`salary\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`updatedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`departmentName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`deletedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`createdBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`department\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`updatedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`phoneNumber\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`lastName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`hireDate\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`firstName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`deletedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`createdBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`employee\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`updatedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`minSalary\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`maxSalary\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`jobTitle\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`deletedBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`createdBy\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`aut_unique_username_type_deleted_at\` ON \`aut_credentials\` (\`username\`, \`type\`, \`deletedAt\`)`);
    }

}
